name: tests

on:
  push:
    branches:
      - 'main'
      - '*.*.*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.mdx'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.mdx'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ragflow_tests:
    name: ragflow_tests
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
    runs-on: ["self-hosted", "debug"]
    steps:
      - name: Show PR labels
        run: |
          echo "Workflow triggered by ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "PR labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          fi

      - name: Ensure workspace ownership
        run: echo "chown -R $USER $GITHUB_WORKSPACE" && sudo chown -R $USER $GITHUB_WORKSPACE

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build ragflow:dev-slim (arm64)
        run: |
          RUNNER_WORKSPACE_PREFIX=${RUNNER_WORKSPACE_PREFIX:-$HOME}
          cp -r ${RUNNER_WORKSPACE_PREFIX}/huggingface.co ${RUNNER_WORKSPACE_PREFIX}/nltk_data ${RUNNER_WORKSPACE_PREFIX}/libssl*.deb .
          sudo docker pull ubuntu:24.04
          sudo docker build --build-arg ARCH=arm64 -f Dockerfile.slim -t ghcr.io/${{ github.repository_owner }}/ragflow:dev-slim .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ragflow:dev-slim to ghcr.io (arm64)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ragflow:dev-slim:arm64
          sudo docker tag ghcr.io/${{ github.repository_owner }}/ragflow:dev-slim $IMAGE_NAME
          sudo docker push $IMAGE_NAME

          # Tag and push as latest
          sudo docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/ragflow:dev-slim:latest
          sudo docker push ghcr.io/${{ github.repository_owner }}/ragflow:dev-slim:latest

      - name: Build ragflow:dev (arm64)
        run: |
          sudo docker build --build-arg ARCH=arm64 -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/ragflow:dev .

      - name: Push ragflow:dev to ghcr.io (arm64)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ragflow:dev:arm64
          sudo docker tag ghcr.io/${{ github.repository_owner }}/ragflow:dev $IMAGE_NAME
          sudo docker push $IMAGE_NAME

          # Tag and push as latest
          sudo docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/ragflow:dev:latest
          sudo docker push ghcr.io/${{ github.repository_owner }}/ragflow:dev:latest

      - name: Start ragflow:dev-slim
        run: |
          sudo docker compose -f docker/docker-compose.yml up -d

      - name: Stop ragflow:dev-slim
        if: always()
        run: |
          sudo docker compose -f docker/docker-compose.yml down -v

      - name: Start ragflow:dev
        run: |
          echo "RAGFLOW_IMAGE=ghcr.io/${{ github.repository_owner }}/ragflow:dev" >> docker/.env
          sudo docker compose -f docker/docker-compose.yml up -d

      - name: Stop ragflow:dev
        if: always()
        run: |
          sudo docker compose -f docker/docker-compose.yml down -v
